export interface InventorySaleInvoiceDocument {
  id: number;
  numbering_id: number;
  branch_office_id: number;
  third_party_id: number;
  current_numbering: number;
  document_type: string;
  operation_code: string;
  environment_code: string;
  document_number: string;
  due_date: string;
  document_code: string;
  currency_code: string;
  payment_method: string;
  payment_status: string;
  payment_due_date: string;
  advance_payment: number | null;
  total_items: string;
  total_discounts_by_items: string;
  total_global_discounts: string;
  total_charges_by_items: string;
  total_global_charges: string;
  total_taxes_by_items: string;
  total_withholdings_by_items: string;
  total_global_withholdings: string;
  total_to_pay: string;
  invoice_total: string;
  operation_total: string;
  subtotal: string;
  track_id: number | null;
  xml_path: string | null;
  pdf_path: string | null;
  pdf_ticket_path: string | null;
  stamped: boolean;
  saled_at: string | null;
  folio: string | null;
  error_message: string | null;
  cufe_scheme: string | null;
  cufe_value: string | null;
  qr_link: string | null;
  sign_hash: string | null;
  issue_date: string;
  issue_time: string;
  user_shift_id: number;
  created_at: string;
  updated_at: string;
  deleted_at: string | null;
  amount_returned: number | null;
}
